name: Publish Common Package

on:
  push:
    branches:
      - main  # runs only when you push/merge into master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js with GitHub Packages registry
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      # Install dependencies (clean install)
      - name: Install dependencies
        run: npm ci

      # Build TypeScript -> dist/
      - name: Build package
        run: npm run build

      # Publish to GitHub Packages
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
